%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Author: Riley Culberg
% Date: 2024-10-11
%
% Script to generate a GeoTIFF file with the final all Greenland fracture
% probability map from the text file saved to h_AllGreenlandStress.ipynb.
%
% Inputs:
% Text file for fracture probabilities generated by
% h_AllGreenlandStress.ipynb.
%
% Outputs:
% GeoTIFF file with annual fracture probability
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

clear;

% Read in one of the strain rate maps to get the georeferencing information
% so we can apply it to the fracture probabilities which are calculated on
% the exact same grid
in_dir = "C:\Users\rtc84\Documents\Data\Greenland\Crevasses\IceSlabCrevasseData\GrISStrainRate\";
[~, R] = readgeoraster(strcat(in_dir, "Exp0_eXX_Exponential.tif"));

% Read in the fracture probability text file
data = readmatrix("AnnualGreenlandProbability_Final.txt");

% Load the BedMachine ice maks
[bm,~] = readgeoraster("C:\Users\rtc84\Documents\Data\Greenland\BedMachine\Resampled\BM_IceMask_250m.tif");

% Set ice mask to 1 over grounded ice and 0 elsewhere
bm = double(bm(:));
ind = find(bm ~= 2);
bm(ind) = 0;
ind = find(bm == 2);
bm(ind) = 1;
bm = reshape(bm, size(data));

% Mask out all regions not on grounded ice from the fracture probability
% map
data = data.*bm;

% Save a georeferenced GeoTIFF of the fracture probability
geotiffwrite("AnnualProbMap_Final.tif", data, R, "CoordRefSysCode", 3413);